# Generated by Django 5.1.6 on 2025-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_accommodation_college"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="longitude",
            new_name="lon",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="price",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="budget",
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accommodation",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="type",
            field=models.CharField(default="PG", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accommodation",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
