# Generated by Django 5.1.6 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_latitude_accommodation_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "alternate_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("college_or_workplace", models.CharField(max_length=150)),
                ("course", models.CharField(blank=True, max_length=100, null=True)),
                ("accommodation", models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name="Accommodation",
        ),
        migrations.DeleteModel(
            name="College",
        ),
    ]
