# Generated by Django 5.1.6 on 2025-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile_delete_accommodation_delete_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="alternate_contact_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
